### ISSUE TITLE
Support hiding of settings pane

### ISSUE THREAD

**Issue by noopkat** [noopkat/electric-io#11]

**Comment by escherina** [comment]
I can take this one! @noopkat - what would be your preferred way to hide the panel? I was thinking to collapse it, like an accordion. Since it's pinned to the right hand side of the screen by default, it could collapse into a horizontal bar, a vertical bar - or something smaller.

I put together a few options [in Figma here](https://www.figma.com/file/NBSU5KlAwKxDgp0CPbw9aLdJ/Electric-IO-settings-panel-options). I think the settings icon version (option 3) might be good for mobile, but otherwise the horizontal bar version (option 1) seems the most obvious for the user.

**Comment by noopkat** [comment]
Hi @escherina!

Thank you so much for the Figma mockups! Super helpful. Let's go with Option 3 (the gear!) 💯
