### ISSUE TITLE
Support changing app title

### ISSUE THREAD

**Issue by noopkat** [noopkat/electric-io#12]
The app title says '⚡️electric io' right now but who really cares if it doesn't stay that way.
It would be cool to let people change it to say whatever they want!

+ [ ] create a new property called `title` in the dashboard.json settings
+ [ ] set the default value of the property in the json file to be `⚡️electric io` (check lib/helpers.js)
+ [ ] create a new text input field in the dashboard settings form for changing the title (follow the strategy for the background color field)
+ [ ] ensure that the title setting is saved correctly to the dashboard.json file when the 'save' button is clicked in the dashboard settings interface

**Comment by mpaarating** [comment]
I can grab this one!

**Comment by brandon-tabaczynski** [comment]
As per the ask, I looked into the regex thing, but I believe a more simple solution could be the ability to change the title with a Javascript action in the/a Settings page (if this is a desired action), it could most likely find homage near color options, font, etc. If such a result is desired for the individual user, I could || can code the functionality.

**Comment by mpaarating** [comment]
Hey @brandon-tabaczynski, I think I might have been super unclear about the help I was looking for. If you look at this (PR)[https://github.com/noopkat/electric-io/pull/31], we can change the title in a similar manner to the rest of the dashboard settings. The (constants)[https://github.com/mpaarating/electric-io/blob/d515c333f8b67dca313e582be6a62788c3a07736/public/js/utils/constants.js] file has a regex for pulling out an emoji at the beginning of the title into it's own capture group (this is so we can apply a specific class to the emoji to align it with text). I was hoping that the regex could be modified to detect _all_ emoji and put them into their respective capture groups so that we can apply the styling. 

For reference, I found the regex in (this blog post)[https://medium.com/reactnative/emojis-in-javascript-f693d0eb79fb].
